# Generated by Django 2.0.2 on 2018-05-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180504_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.CharField(default='Input Text', max_length=400),
        ),
    ]
