# Generated by Django 2.0.2 on 2018-05-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(),
        ),
    ]
