# Generated by Django 2.0.2 on 2018-05-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180505_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='body',
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(),
        ),
    ]
